### ISSUE TITLE
Possibly missing a street? Or imagery?

### ISSUE THREAD

**Issue by aileenzeng** [ProjectSidewalk/SidewalkWebpage#1622]
This is an issue that I'm running into on my dev environment. I am using the Newberg database at the moment. I already ran the query mentioned in #1570, so I'm not sure if this is a related issue or not. There isn't any infinite page reload - it's just stuck at the loading gif.

First time loading the audit page:
![image](https://user-images.githubusercontent.com/25534091/55672832-9877dc80-5854-11e9-986c-3fcc17b80b1e.png)

After I refreshed the audit page:
![image](https://user-images.githubusercontent.com/25534091/55672880-1f2cb980-5855-11e9-8ae3-b55be0f38c9f.png)

This is what appears in my sbt console:
```
! @7be8oglb8 - Internal server error, for (GET) [/task/street/15250] ->

play.api.Application$$anon$1: Execution exception[[NoSuchElementException: Invoker.first]]
	at play.api.Application$class.handleError(Application.scala:296) ~[play_2.10-2.3.8.jar:2.3.8]
	at play.api.DefaultApplication.handleError(Application.scala:402) [play_2.10-2.3.8.jar:2.3.8]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:205) [play_2.10-2.3.8.jar:2.3.8]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:202) [play_2.10-2.3.8.jar:2.3.8]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33) [scala-library-2.10.5.jar:na]
Caused by: java.util.NoSuchElementException: Invoker.first
	at scala.slick.jdbc.Invoker$$anonfun$first$1.apply(Invoker.scala:36) ~[slick_2.10-2.1.0.jar:0.8.0]
	at scala.slick.jdbc.Invoker$$anonfun$first$1.apply(Invoker.scala:36) ~[slick_2.10-2.1.0.jar:0.8.0]
	at scala.Option.getOrElse(Option.scala:120) ~[scala-library-2.10.5.jar:na]
	at scala.slick.jdbc.Invoker$class.first(Invoker.scala:36) ~[slick_2.10-2.1.0.jar:0.8.0]
	at scala.slick.jdbc.StatementInvoker.first(StatementInvoker.scala:16) ~[slick_2.10-2.1.0.jar:0.8.0]
```

**Comment by aileenzeng** [comment]
Update: I reloaded my database (newberg) and it is still doing this.

**Comment by aileenzeng** [comment]
Oops, I realized what my problem was! I forgot to update the `city-id` parameter to `newberg-or` in `conf` > `cityparams.conf` 😅 Closing this issue.
