### ISSUE TITLE
Can't Get Past the Tutorial: Constant Refreshing Bug

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#1643]
Now that we have ~85 HCDE students using Project Sidewalk for their coursework, we are, unsurprisingly, seeing some new bugs. Here's one that has come up multiple times (that I know of) and it seems very significant (almost a deal breaker for our officially planned Seattle launch this week). Because we don't test the tutorial sequence as much (at least I don't), it's obvious more vulnerable to bugs seeping through.

I have very limited details (what you see below is what I know). I can supply the email addresses for these students so we can follow-up directly. 

Perhaps this is related to https://github.com/ProjectSidewalk/SidewalkWebpage/issues/1563? (If the problem is related to #1563, then perhaps we can have students select a new neighborhood to get around the issue?). **Update**: We've determined that this is not related to #1563.

Student 1:
> I’m trying to do the 3 missions for the Project Sidewalk assignment but every time I try to start exploring and labeling it takes me to the tutorial over and over again. I have tried clicking “have done the tutorial already” button and the page refreshes to the same tutorial page and I’m not sure what to do or how to start. 

Student 2:
> Hello, I do not have a problem with doing the validation, but for the labeling missions, I can't seem to get past the tutorial (done it several times, can't get passed it). Do you know if this is an issue that other people have encountered? The website says it is optimized for chrome and I am doing it in chrome. Any help would be appreciated.

Student 3:
> I was doing the Project Sidewalk assignment and I went through the tutorial, but after I finished it the website wouldn't allow me to do the three labeling missions. Instead it would redirect me to the tutorial over and over again, do you know any solutions to this glitch?

Student 4:
> I have another question, it is about Project Sidewalk. I am trying to explore and mark the curb's, but it keeps sending me back to the tutorial and it won't let me "skip the tutorial" and I am signed on with my UW account. I was able to do the 10 verification's but not the missions. Please let me know what you think, thank you!

Student 5:
> I have been trying to do the 3 labeling missions, but it just makes me do the tutorial over and over. I am signed in and have tried it in multiple browsers with all the security settings off & cookies enabled and still can’t do it. However, the validation works and I did 7 or 8 of those. I also tried creating a different account and that didn’t work either, I do not know if others have been experiencing this, but I do not know how to complete the assignment at the moment though I will try once more on a computer lab computer tomorrow evening.

Student 6:
> I'm trying to do the labeling missions for the Project Sidewalk assignment due tonight but it won't let me get past the tutorial. I've done it three times but after I finish, it leads me back to the tutorial page and won't let me do any other missions.
>
> Have other people been experiencing this difficult? What should I do? 

Student 7:
> I am experiencing issues with the project sidewalk website. I completed the validation missions without any problems, but I cannot access the labeling missions. Each time I try, I am prompted to retake the tutorial. I have completed the tutorial 4 times, but each time I am taken back to the pre-tutorial screen, which I am not able to skip.
> 
> Has anyone else had issues with it? I will do my best to complete the assignment anyway. I would appreciate any insight into the problem.

One unfortunate consequence of this (beyond the inconvenience to the students and the teaching staff--which is significant) is that students are being told to do missions at the UW library. Though this may be a workable solution, those students will be less likely to do more than the minimum missions--which was something I was interested in looking at.

**Comment by aileenzeng** [comment]
I was just able to recreate this bug (twice). I'm not on the `develop` branch at the moment, and I'll check to see if this works there as well.

If I sign in as a user and visit
`http://0.0.0.0:9000/audit?retakeTutorial=true`, it won't let me move onto an onboarding mission unless I have completed the tutorial. 

I haven't been able to confirm if this persists even after I have completed the tutorial because I'm also having some trouble completing the tutorial. There seems to be a bug where the tutorial won't allow me to move on unless I've applied a tag to the NoSidewalk label (even though I've already applied it). (This is also not on the `develop` branch either):
![image](https://user-images.githubusercontent.com/25534091/56168005-b220ce80-5f8e-11e9-8076-19dcf9809fbf.png)

**Comment by aileenzeng** [comment]
I'm not sure if this is related or not, but I just noticed I had some other errors that popped up in my `sbt` console. This happened sometime during the tutorial:
```
[error] application - No timestamp given for a new label
[error] play - Cannot invoke the action, eventually got an error: org.postgresql.util.PSQLException: ERROR: insert or update on table "label" violates foreign key constraint "label_audit_task_id_fkey"
  Detail: Key (audit_task_id)=(15432) is not present in table "audit_task".
[error] application - 

! @7bgnoo564 - Internal server error, for (POST) [/task] ->

play.api.Application$$anon$1: Execution exception[[PSQLException: ERROR: insert or update on table "label" violates foreign key constraint "label_audit_task_id_fkey"
  Detail: Key (audit_task_id)=(15432) is not present in table "audit_task".]]
	at play.api.Application$class.handleError(Application.scala:296) ~[play_2.10-2.3.8.jar:2.3.8]
	at play.api.DefaultApplication.handleError(Application.scala:402) [play_2.10-2.3.8.jar:2.3.8]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [play_2.10-2.3.8.jar:2.3.8]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [play_2.10-2.3.8.jar:2.3.8]
	at scala.Option.map(Option.scala:145) [scala-library-2.10.5.jar:na]
Caused by: org.postgresql.util.PSQLException: ERROR: insert or update on table "label" violates foreign key constraint "label_audit_task_id_fkey"
  Detail: Key (audit_task_id)=(15432) is not present in table "audit_task".
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2198) ~[postgresql-9.3-1102-jdbc4.jar:na]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1927) ~[postgresql-9.3-1102-jdbc4.jar:na]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255) ~[postgresql-9.3-1102-jdbc4.jar:na]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561) ~[postgresql-9.3-1102-jdbc4.jar:na]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:419) ~[postgresql-9.3-1102-jdbc4.jar:na]
[error] play - Cannot invoke the action, eventually got an error: org.postgresql.util.PSQLException: ERROR: insert or update on table "label" violates foreign key constraint "label_audit_task_id_fkey"
  Detail: Key (audit_task_id)=(15432) is not present in table "audit_task".
[error] application - 

! @7bgnood1m - Internal server error, for (POST) [/task] ->

play.api.Application$$anon$1: Execution exception[[PSQLException: ERROR: insert or update on table "label" violates foreign key constraint "label_audit_task_id_fkey"
  Detail: Key (audit_task_id)=(15432) is not present in table "audit_task".]]
	at play.api.Application$class.handleError(Application.scala:296) ~[play_2.10-2.3.8.jar:2.3.8]
	at play.api.DefaultApplication.handleError(Application.scala:402) [play_2.10-2.3.8.jar:2.3.8]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [play_2.10-2.3.8.jar:2.3.8]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [play_2.10-2.3.8.jar:2.3.8]
	at scala.Option.map(Option.scala:145) [scala-library-2.10.5.jar:na]
Caused by: org.postgresql.util.PSQLException: ERROR: insert or update on table "label" violates foreign key constraint "label_audit_task_id_fkey"
  Detail: Key (audit_task_id)=(15432) is not present in table "audit_task".
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2198) ~[postgresql-9.3-1102-jdbc4.jar:na]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1927) ~[postgresql-9.3-1102-jdbc4.jar:na]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255) ~[postgresql-9.3-1102-jdbc4.jar:na]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561) ~[postgresql-9.3-1102-jdbc4.jar:na]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:419) ~[postgresql-9.3-1102-jdbc4.jar:na]
[error] application - No timestamp given for a new label
[error] play - Cannot invoke the action, eventually got an error: org.postgresql.util.PSQLException: ERROR: insert or update on table "label" violates foreign key constraint "label_audit_task_id_fkey"
  Detail: Key (audit_task_id)=(15432) is not present in table "audit_task".
[error] application - 

! @7bgnool4k - Internal server error, for (POST) [/task] ->

play.api.Application$$anon$1: Execution exception[[PSQLException: ERROR: insert or update on table "label" violates foreign key constraint "label_audit_task_id_fkey"
  Detail: Key (audit_task_id)=(15432) is not present in table "audit_task".]]
	at play.api.Application$class.handleError(Application.scala:296) ~[play_2.10-2.3.8.jar:2.3.8]
	at play.api.DefaultApplication.handleError(Application.scala:402) [play_2.10-2.3.8.jar:2.3.8]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [play_2.10-2.3.8.jar:2.3.8]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [play_2.10-2.3.8.jar:2.3.8]
	at scala.Option.map(Option.scala:145) [scala-library-2.10.5.jar:na]
Caused by: org.postgresql.util.PSQLException: ERROR: insert or update on table "label" violates foreign key constraint "label_audit_task_id_fkey"
  Detail: Key (audit_task_id)=(15432) is not present in table "audit_task".
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2198) ~[postgresql-9.3-1102-jdbc4.jar:na]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1927) ~[postgresql-9.3-1102-jdbc4.jar:na]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255) ~[postgresql-9.3-1102-jdbc4.jar:na]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561) ~[postgresql-9.3-1102-jdbc4.jar:na]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:419) ~[postgresql-9.3-1102-jdbc4.jar:na]
```

**Comment by jonfroehlich** [comment]
Can you click 'skip' for the tutorial? Does that allow you to bypass?

**Comment by jonfroehlich** [comment]
I asked one of the students experiencing this problem to try and manually select a new neighborhood from the landing page but this didn't work:

> So when I did that yesterday (picking diff neighborhood), I would still have the same issue, but it'd say I'm in a different neighborhood. So nothing really changed.

**Comment by aileenzeng** [comment]
Nope -- it looks like what's happening is that there's some issue with getting the mission to be logged as completed/skipped. I'm pretty sure it's related to some asynchronous weirdness on the front-end -- still digging.

**Comment by jonfroehlich** [comment]
Unfortunately, students continue to be burdened by this bug and it's a showstopper (it prevents the students from actually completing the assignment). Is there anyway of pushing a fix for what @andrew4699 found soon (https://github.com/ProjectSidewalk/SidewalkWebpage/pull/1645#issuecomment-483524868)?

**Comment by misaugstad** [comment]
I mean if it still isn't done that will be my number 1 priority tomorrow morning. I think that is probably when it will get on production tbh

**Comment by jonfroehlich** [comment]
Thanks @misaugstad. I realize you are on vacation, and it's important to me that we respect this boundary. So, while I think we got close to resolving this on our own, I think we'll need your help. Students are still emailing the instructor quite frequently about this bug.

**Comment by jonfroehlich** [comment]
Unfortunately, a Seattle Times reporter who was interested in checking out our work (to see if it was story worthy, I imagine), just experienced this bug as well. Ugh!

Reporter:
> I was playing around with the system, and I kept getting redirected to take the tutorial. I was trying to get through and explore my neighborhood. Do you know how to move past the tutorial?

**Comment by misaugstad** [comment]
@jonfroehlich tell them to try Firefox for now

**Comment by jonfroehlich** [comment]
But with Firefox, the label stickiness is broken, see: https://github.com/ProjectSidewalk/SidewalkWebpage/issues/1644

**Comment by misaugstad** [comment]
oh my
