### ISSUE TITLE
ValueError: invalid literal for long() with base 10: '20 de Noviembre' in check_streets_for_imagery.py

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#2908]
I've been playing around with https://github.com/ProjectSidewalk/SidewalkWebpage/blob/develop/check_streets_for_imagery.py.

But I just received an error  when using this `street_edge_endpoints.csv` file for La Piedad: https://www.dropbox.com/s/kkrasuads5j0df9/street_edge_endpoints.csv?dl=0 

It looks like the GSV API returned a Spanish formatted date that we barfed on:

```
100.00% complete
Traceback (most recent call last):
  File "d:/Dropbox/ProjectSidewalk_LaPiedad/GSVCaptureDateAnalysis/check_streets_for_imagery.py", line 120, in <module>
    write_output(streets_with_no_imagery, None)
  File "d:/Dropbox/ProjectSidewalk_LaPiedad/GSVCaptureDateAnalysis/check_streets_for_imagery.py", line 22, in write_output
    no_imagery_df.region_id = no_imagery_df.region_id.astype('int32')
  File "C:\Python27\lib\site-packages\pandas\core\generic.py", line 5691, in astype
    **kwargs)
  File "C:\Python27\lib\site-packages\pandas\core\internals\managers.py", line 531, in astype
    return self.apply('astype', dtype=dtype, **kwargs)
  File "C:\Python27\lib\site-packages\pandas\core\internals\managers.py", line 395, in apply
    applied = getattr(b, f)(**kwargs)
  File "C:\Python27\lib\site-packages\pandas\core\internals\blocks.py", line 534, in astype
    **kwargs)
  File "C:\Python27\lib\site-packages\pandas\core\internals\blocks.py", line 633, in _astype
    values = astype_nansafe(values.ravel(), dtype, copy=True)
  File "C:\Python27\lib\site-packages\pandas\core\dtypes\cast.py", line 683, in astype_nansafe
    return lib.astype_intsafe(arr.ravel(), dtype).reshape(arr.shape)
  File "pandas\_libs\lib.pyx", line 546, in pandas._libs.lib.astype_intsafe
ValueError: invalid literal for long() with base 10: '20 de Noviembre'
```
Also, @misaugstad, should we consider moving these utility scripts out of the main webpage repo and into like a ProjectSidewalk/utilities repo or do they get called by our web server during deployment?

**Comment by jonfroehlich** [comment]
I seem to remember now that Mikey switched up this column for me from a `region_id` to a `region_name` — and that the problem is, we just inserted the region name strings into the column `region_id`, which is triggering this exception.

I think the ideal would be to have both for my purposes.

**Comment by misaugstad** [comment]
Which line are you getting that error on? Because I've never run into that. But in `check_streets_for_imagery.py`, we never actually look at more of the response than just seeing if it succeeded/failed, so that may be why I never ran into this issue.

I don't see how switching neighborhood names into the `region_id` column would be triggering the issue you're seeing here.

I'm assuming that you made modifications to this script when you ran it?

**Comment by jonfroehlich** [comment]
It's this line:
```
no_imagery_df.region_id = no_imagery_df.region_id.astype('int32')
```

And it's definitely because we are trying to convert a non-numeric string to an int32. Closing this issue because it's due to how you formatted the input csv to me (you put names into the region_id column)
