### ISSUE TITLE
Disagree no longer works in validate

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3400]
I tried to click disagree and got an exception.

![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/02296366-ce91-4458-9747-c3b03876980f)

**Comment by hoominchu** [comment]
I was not able to reproduce this.

**Comment by misaugstad** [comment]
I also could not reproduce this anywhere. I took a look at where the error message originates... It is some code that I touched recently, but there shouldn't be any issues with it... Let's leave it open for a little while and see if it pops up again. If it happens occasionally, it might be some sort of race condition and we may need to enforce an ordering of some code execution somewhere

**Comment by jonfroehlich** [comment]
Had this happen again on the exact same image in Walla Walla. Perhaps it's something unique to that pano?

Notice how the curb ramp label seems way off too.

```
Uncaught ReferenceError: zoom is not defined
    at Label.validate (SVValidate.js:912:94)
    at PanoramaContainer.validateLabel (SVValidate.js:2794:40)
    at validateLabel (SVValidate.js:1281:35)
    at HTMLButtonElement.<anonymous> (SVValidate.js:1247:9)
    at HTMLButtonElement.dispatch (jquery-1.12.2.min.js:3:12444)
    at r.handle (jquery-1.12.2.min.js:3:9173)
```

**Comment by jonfroehlich** [comment]
It's not just about 'agree' or 'disagree' but the buttons become non-functional.

It's pretty easy to replicate this problem in Walla Walla. I've run into it pretty darn quickly when validating these (while multitasking during a Zoom call). @misaugstad, I think you'll see this if you try to investigate on Walla Walla.

Note that the placed label always seems to be way off--so something isn't be recorded correctly (or the Zoom isn't being set correctly— @misaugstad recently updated the zoom code in the validation UI and my guess is something here is triggering the bug).

![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/18684f86-cb15-4161-a76e-2693e8c28638)

```
Uncaught ReferenceError: zoom is not defined
    at Label.validate (SVValidate.js:912:94)
    at PanoramaContainer.validateLabel (SVValidate.js:2794:40)
    at validateLabel (SVValidate.js:1281:35)
    at HTMLButtonElement.<anonymous> (SVValidate.js:1251:9)
    at HTMLButtonElement.dispatch (jquery-1.12.2.min.js:3:12444)
    at r.handle (jquery-1.12.2.min.js:3:9173)
```

**Comment by bgoblirsch** [comment]
I believe this is happening when the validator is zoomed in—that's when I get the error. If I zoom back out, then I am able to include text when I click disagree.

**Comment by bgoblirsch** [comment]
This happens on every validation I try to disagree with, so I am never able to attach a message.

**Comment by jonfroehlich** [comment]
Hmm, try reloading. Something is definitely up with this. We will investigate. Thanks for your comment @bgoblirsch

**Comment by bgoblirsch** [comment]
@jonfroehlich This bug has occurred since I started project sidewalk about a month ago. I've never been able to attach a message.

**Comment by jonfroehlich** [comment]
OK. Thanks for letting us know.

**Comment by misaugstad** [comment]
Thank you @bgoblirsch! The issue has to do with inputting a message along with a validation. This will make it much easier to track down!
