### ISSUE TITLE
Clustering seems to be broken

### ISSUE THREAD

**Issue by misaugstad** [ProjectSidewalk/SidewalkWebpage#3478]
##### Brief description of problem/feature
When I try to run clustering manually, I see errors like this in the logs (trimmed to only show relevant parts):
```
! @84cojlagk - Internal server error, for (GET) [/runClustering?clusteringType=both] ->

play.api.Application$$anon$1: Execution exception[[RuntimeException: Nonzero exit value: 1]]
...
Caused by: java.lang.RuntimeException: Nonzero exit value: 1
        ...
	at controllers.helper.AttributeControllerHelper$$anonfun$runSingleUserClustering$3.apply(AttributeControllerHelper.scala:65) ~[sidewalk-webpage.sidewalk-webpage-7.18.0.jar:7.18.0]
	at controllers.helper.AttributeControllerHelper$$anonfun$runSingleUserClustering$3.apply(AttributeControllerHelper.scala:62) ~[sidewalk-webpage.sidewalk-webpage-7.18.0.jar:7.18.0]
        ...
	at controllers.helper.AttributeControllerHelper$.runSingleUserClustering(AttributeControllerHelper.scala:62) ~[sidewalk-webpage.sidewalk-webpage-7.18.0.jar:7.18.0]
	at controllers.helper.AttributeControllerHelper$.runClustering(AttributeControllerHelper.scala:20) ~[sidewalk-webpage.sidewalk-webpage-7.18.0.jar:7.18.0]
	at controllers.AttributeController$$anonfun$runClustering$1.apply(AttributeController.scala:68) ~[sidewalk-webpage.sidewalk-webpage-7.18.0.jar:7.18.0]
	at controllers.AttributeController$$anonfun$runClustering$1.apply(AttributeController.scala:66) ~[sidewalk-webpage.sidewalk-webpage-7.18.0.jar:7.18.0]
```

And taking a look at the logs of the nightly clustering, some of them just look like this, where they hang on the first user and never complete:
```
2024-02-01 08:00:00,959 - [INFO] - from application in application-akka.actor.default-dispatcher-11 
Auto-scheduled clustering of label attributes starting at: Thu Feb 01 16:00:00 UTC 2024

2024-02-01 08:00:01,004 - [INFO] - from application in application-akka.actor.default-dispatcher-11 
N users = 17

2024-02-01 08:00:01,004 - [INFO] - from application in application-akka.actor.default-dispatcher-11 
Finished 0.00% of users, next: d4da258c-425f-4f1f-95e8-9bd8f5d6bfb8.
```

And some of them start throwing errors like this:
```
2024-02-01 03:00:00,835 - [INFO] - from application in application-akka.actor.default-dispatcher-10 
Auto-scheduled clustering of label attributes starting at: Thu Feb 01 11:00:00 UTC 2024

2024-02-01 03:00:01,458 - [INFO] - from application in application-akka.actor.default-dispatcher-10 
N users = 200

2024-02-01 03:00:01,458 - [INFO] - from application in application-akka.actor.default-dispatcher-10 
Finished 0.00% of users, next: 9d3db893-2f80-4dd4-85c3-43280cbc7a66.

2024-02-01 07:25:09,248 - [ERROR] - from play.nettyException in New I/O worker #62 
Exception caught in Netty
java.lang.IllegalArgumentException: empty text
	at org.jboss.netty.handler.codec.http.HttpVersion.<init>(HttpVersion.java:97) ~[io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.handler.codec.http.HttpVersion.valueOf(HttpVersion.java:62) ~[io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.handler.codec.http.HttpRequestDecoder.createMessage(HttpRequestDecoder.java:75) ~[io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.handler.codec.http.HttpMessageDecoder.decode(HttpMessageDecoder.java:191) ~[io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.handler.codec.http.HttpMessageDecoder.decode(HttpMessageDecoder.java:102) ~[io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:500) ~[io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) ~[io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) [io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [io.netty.netty-3.9.9.Final.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_402]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_402]
	at java.lang.Thread.run(Thread.java:750) [na:1.8.0_402]
```

I can't reproduce this on my local dev environment. My guess is that the default Python version on the new servers is Python3 instead of Python2, which is messing with our Python scripts, such as `label_clustering.py`. Will check in with @yhtill. @justyeethan wrote a PR (#3300) that works towards upgrading everything to Python 3, so hopefully we can use most of that to do the upgrade if that's what our current issue is.

**Comment by misaugstad** [comment]
Confirmed that this is because the only versions of Python installed on the new system are 3.9 (the default) and 3.11. Seems like a good time to make the upgrade. In #3300 the upgrade is made to Python 3.7. Not sure what the reason was to only go to 3.7, but I'll see if I can get it up to 3.9.

**Comment by misaugstad** [comment]
closing via #3300
