### ISSUE TITLE
St. Louis Deployment: Can't Start Explore

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/SidewalkWebpage#3532]
Can't make it out of the tutorial.

Click skip lesson.

![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/063b0788-1f37-49a1-a560-4bb9f970cb47)

```
SVLabel.js:7024 Uncaught TypeError: Cannot read properties of undefined (reading 'lat')
    at Object.getPosition (SVLabel.js:7024:30)
    at NavigationModel.getPosition (SVLabel.js:8106:48)
    at Form.compileSubmissionData (SVLabel.js:3262:42)
    at Tracker.submitForm (SVLabel.js:1907:33)
    at Tracker.push (SVLabel.js:1895:18)
    at HTMLDocument.<anonymous> (SVLabel.js:1704:18)
    at HTMLDocument.dispatch (jquery-1.12.2.min.js:3:12444)
    at r.handle (jquery-1.12.2.min.js:3:9173)

Uncaught TypeError: Cannot read properties of undefined (reading 'heading')
    at updatePov (SVLabel.js:7791:13)
    at SVLabel.js:6783:13
    at dispatch (jquery-1.12.2.min.js:3:12444)
    at r.handle (jquery-1.12.2.min.js:3:9173)

Uncaught TypeError: Cannot read properties of undefined (reading 'heading')
    at updatePov (SVLabel.js:7791:13)
    at SVLabel.js:6783:13
    at dispatch (jquery-1.12.2.min.js:3:12444)
    at r.handle (jquery-1.12.2.min.js:3:9173)
```

**Comment by jonfroehlich** [comment]
Here's a video in a fresh Edge install (this time: I didn't use Chrome in case there was some caching issue). So, getting bug in Firefox, Edge, and Chrome.

https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/4f5d8ee7-d02f-4b38-8eb6-539231f62524

**Comment by jonfroehlich** [comment]
And if I instead click on "start tutorial", I get:

![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/5042bcf9-bd09-4bab-a400-0d6db7a7e51f)

![image](https://github.com/ProjectSidewalk/SidewalkWebpage/assets/1621749/f7d2b4d5-6e25-4c79-ac44-39e0c99c37ef)
